spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ipl_prod
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  cache:
    redis:
      time-to-live: 1200000  # 20 minutes in production
server:
  port: 8080  # Production port
