spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ipl2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: assignment
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes in milliseconds
      cache-null-values: false
      use-key-prefix: true
  redis:
    host: localhost
    port: 6379  # Default Redis port
    # password: your_redis_password  # Uncomment and set if your Redis requires authentication
  kafka:
    bootstrap-servers: localhost:9092  # Adjust if your Kafka broker is elsewhere
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  logging:
    level:
      org.springframework.cache: DEBUG
      org.springframework.data.redis: DEBUG
      org.springframework.kafka: DEBUG

server:
  port: 5050